export type Product = { id:string; name:string; category:string; price:number; color:string; image:string; description:string; isNew?:boolean };
export const products: Product[] = [
 { id:"arc-lamp", name:"Arc Table Lamp", category:"Home", price:128, color:"#e5d9c8", image:"https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=85", description:"A sculptural glow for slow evenings. Brushed brass, opal glass and a warm dimmable light." },
 { id:"daily-tote", name:"Daily Carry Tote", category:"Accessories", price:74, color:"#d3dfcf", image:"https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=900&q=85", description:"Roomy, sturdy and made for everything. Woven recycled canvas with vegetable-tanned handles.", isNew:true },
 { id:"cloud-mug", name:"Cloud Ceramic Mug", category:"Kitchen", price:32, color:"#d8e2e9", image:"https://images.unsplash.com/photo-1514228742587-6b1558fcf93a?auto=format&fit=crop&w=900&q=85", description:"A soft handle and a hand-glazed finish make this your new morning ritual." },
 { id:"linen-throw", name:"Linen Throw", category:"Home", price:96, color:"#ead5ce", image:"https://images.unsplash.com/photo-1583845112203-454c7e3f2b7d?auto=format&fit=crop&w=900&q=85", description:"Washed European linen, woven to get softer with every season. 140 × 200cm.", isNew:true },
 { id:"stone-vase", name:"Stoneware Vase", category:"Home", price:58, color:"#d9d3c7", image:"https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=900&q=85", description:"A quiet shape for loud flowers. Hand-thrown stoneware with a matte finish." },
 { id:"studio-notebook", name:"Studio Notebook", category:"Stationery", price:24, color:"#c8d9e4", image:"https://images.unsplash.com/photo-1531346680769-a1d79b57de5c?auto=format&fit=crop&w=900&q=85", description:"Ideas deserve a beautiful place to land. 160 pages of smooth recycled paper." }
];
export const categories = ["All pieces", "Home", "Accessories", "Kitchen", "Stationery"];